<?php

namespace Modules\Cms\Enums;

enum UploadTypeEnum: string
{
    case CMS_BANNER = 'CMS_BANNER';
    case CMS_FEEDBACK_STUDENT_AVATAR = 'CMS_FEEDBACK_STUDENT_AVATAR';
    case CMS_CATEGORY_THUMBNAIL = 'CMS_CATEGORY_THUMBNAIL';
    case CMS_FAQ_CATEGORY_THUMBNAIL = 'CMS_FAQ_CATEGORY_THUMBNAIL';
    case CMS_INSTRUCTOR_AVATAR = 'CMS_INSTRUCTOR_AVATAR';
    case CMS_BLOG_IMAGE = 'CMS_BLOG_IMAGE';
    case CMS_COURSE_AVATAR = 'CMS_COURSE_AVATAR';
    case CMS_COURSE_PREVIEW_VIDEO = 'CMS_COURSE_PREVIEW_VIDEO';
    case CMS_COURSE_WEBSITE_LOGO = 'CMS_COURSE_WEBSITE_LOGO';
    case CMS_COURSE_WEBSITE_FAVICON = 'CMS_COURSE_WEBSITE_FAVICON';
}
