<?php

namespace Modules\Lms\Enums;

enum LmsUploadTypeEnum: string
{
    case AVATAR_WORKSPACE = 'AVATAR_WORKSPACE';
    case BACKGROUND_WORKSPACE = 'BACKGROUND_WORKSPACE';
    case WORKSPACE_WEBSITE_LOGO = 'WORKSPACE_WEBSITE_LOGO';
    case WORKSPACE_WEBSITE_FAVICON = 'WORKSPACE_WEBSITE_FAVICON';
    case FILE_ATTACH_NOTIFICATION_CONFIG = 'FILE_ATTACH_NOTIFICATION_CONFIG';
    case SUBJECT_AVATAR_URL = 'SUBJECT_AVATAR_URL';
}
